# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Редиска",
  "description": "Нехороший человек"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/3/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "ул. Мира, 1",
  "positions": [
    {
      "product": 4,
      "quantity": 999,
      "price": 120.50
    },
    {
      "product": 2,
      "quantity": 999,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/2/
Content-Type: application/json

{
  "positions": [
    {
      "product": 4,
      "quantity": 1000,
      "price": 130.80
    },
    {
      "product": 2,
      "quantity": 230,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json

###

# создание пустого склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": []
}

###

# получение складов
GET {{baseUrl}}/stocks/
Content-Type: application/json

###

# удаление склада
DELETE {{baseUrl}}/stocks/6/
Content-Type: application/json

###
# поиск продуктов
GET {{baseUrl}}/products/?search=помид
Content-Type: application/json

###
# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?search=помид
Content-Type: application/json